name: Lint Check

on:
  workflow_call:
  pull_request:

jobs:
  clang-tidy:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/cavise/artery-gh-runner:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Run clang-tidy
        uses: ZedThree/clang-tidy-review@v0.23.0
        id: review
        with:
          build_dir: build/Debug
          cmake_command: |
            python3 tools/build.py -cl       \
              --generator Ninja               \
              -D WITH_SIMULTE:BOOL=ON         \
              -D WITH_OTS:BOOL=ON             \
              -D WITH_TESTBED:BOOL=ON         \
              -D WITH_TRANSFUSION:BOOL=ON     \
              -D CMAKE_EXPORT_COMPILE_COMMANDS=ON
            
            cmake --build build/Debug --target artery-codegen

      - name: Upload clang-tidy fixes
        if: always()
        uses: ZedThree/clang-tidy-review/upload@v0.23.0
