name: Lint Check

on:
  workflow_call:

jobs:
  clang-tidy:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/cavise/artery-gh-runner:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Configure CMake
        run: |
          tools/build.py -cl              \
            --generator Ninja             \
            -D WITH_SIMULTE:BOOL=ON       \
            -D WITH_OTS:BOOL=ON           \
            -D WITH_TESTBED:BOOL=ON       \
            -D WITH_TRANSFUSION:BOOL=ON   \
            -D CMAKE_EXPORT_COMPILE_COMMANDS=ON


      - name: Build Artery codegen target
        run: cmake --build build/Debug --target artery-codegen

      - name: Fix git safe directory
        run: git config --global --add safe.directory $GITHUB_WORKSPACE

      - name: Clang-Tidy Review
        uses: ZedThree/clang-tidy-review@v0.22.0
        id: review
        with:

          token: ${{ secrets.GITHUB_TOKEN }}
          build_dir: build/Debug
          split_workflow: false