name: CI on main branch

on:
<<<<<<< current
=======
  push:
    branches: [master]
>>>>>>> incoming
  pull_request:
    branches: [master]

jobs:
  lint:
    uses: ./.github/workflows/lint.yaml

  test:
    uses: ./.github/workflows/test.yaml
