<<<<<<< current
name: Prepare GitHub containers

on:
  push:
    branches: [main]
  workflow_call:

jobs:
  build-base:
=======
name: Prepare GitHub container

on:
  push:
    branches: [master]
  workflow_call:

jobs:
  build-docker-image:
>>>>>>> incoming
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v6
<<<<<<< current
      - uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/cavise/artery:base
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-cached:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        distribution: [arch-linux, debian]

    needs: build-base
    permissions: 
      contents: read
      packages: write

    steps:
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v6
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v3
=======

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3
>>>>>>> incoming

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
<<<<<<< current
          file: .devcontainer/${{ matrix.distribution }}/Dockerfile
          push: true
          target: cached-build
          tags: ghcr.io/cavise/artery-cached:${{ matrix.distribution }}-latest
=======
          push: true
          tags: ghcr.io/riebl/artery-gh-runner:latest
>>>>>>> incoming
          cache-from: type=gha
          cache-to: type=gha,mode=max
